### ISSUE TITLE
[Enhancement]: 使用普通用户进行检测时失败

### ISSUE THREAD

**Issue by xiongmz** [oceanbase/obdiag#78]
### Description

环境信息：独立部署的1.5版本obdiag，主机ssh用admin用户，配置了SSH免密
异常1：所有sysctl参数都取不到，都报错。用root就没此问题
异常2：命令不能执行，实际上在主机上admin用户下可执行
![37712e0ea0dd12be7d4ad8b1f870a36c](https://github.com/oceanbase/oceanbase-diagnostic-tool/assets/11705026/ec9cb316-25c2-4fad-9044-e6fb959a6461)

**Comment by wayyoungboy** [comment]
由于无法直接感知用户的权限级别，因此计划增加文档中的用户权限声明来进行一个透出。
想了解下在出现sysctl参数都取不到的情况时使用的是部署observer的用户么？
Due to the inability to directly perceive the user's permission level, it is planned to add a user permission statement in the document to provide transparency.
I would like to know if the user who deployed the observer was using it when the sysctl parameters were not available?

**Comment by wayyoungboy** [comment]
sysctl获取内核参数部分的task已经全量使用直接读取内核参数的方式进行优化
